[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"

auto_detect_remappings = false # remappings seem to cause problems
optimizer = true

optimizer_runs = 700 # 500 builds & tests but 200 deploys

via_ir = true   # makes the compiler run 7-10 times slower, is good at reducing code size or lower gas usage
deny = "warnings" # enable to stop compilations if there are warnings

remappings = [
  # foundry
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  # openzeppelin
  "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
  "solidity-stringutils/=lib/openzeppelin-foundry-upgrades/lib/solidity-stringutils/",
  # solady
  "@solady/=lib/solady/src/",
  # chainlink
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/v0.8/",
  # bao audited code
  "@bao/=lib/bao-base-audit-2025-07/src/",
  # bao latest
  "@bao-test/=lib/bao-base/test/",
  "@bao-script/=lib/bao-base/script/",
  # bao-factory is a transitive dependency via bao-base
  "@bao-factory/=lib/bao-base/lib/bao-factory/src/",
  "@bao-factory-test/=lib/bao-base/lib/bao-factory/test/",
  # harbor
  "@harbor/=src/",
  "@harbor-script/=script/",
  "@harbor-test/=test/",
  # harbor price aggregators
  "@harbor-price/=src/",
  # retain the below for legacy
  "src/=src/",
  "test/=test/",
]

fuzz.gas_report_samples = 64 # gas report doesn't need so many test cases
gas_reports_ignore = [
  "ERC20Mock",
  "ERC1967Proxy",
  "MockBaoAccessControl",
  "TestTokenDistributor",
  "Useful",
  "MockAggregator",
  "MockWrappedPriceOracle",
]

fs_permissions = [
  { access = "read", path = "./" },
  { access = "read-write", path = "./results" },     # regression files
  { access = "read-write", path = "./deployments" }, # deployment logs
  { access = "read-write", path = "./tmp" },         # temp files - can be removed
]

gas_limit = "18446744073709551615"

[lint]
exclude_lints = ["mixed-case-function", "mixed-case-variable"]
severity = ["gas"]

# slither building profile - removes vyper
[profile.novyper]
skip = ["**/*.vy"]

[vyper]
path = ".venv/bin/vyper"
# version = "0.3.10"
# evm_version = "shanghai" # or "london", "cancun" depending on your target
optimize = "gas"
# optimize_runs = 700
# via_ir = false           # you can enable this later if needed


[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
local = "${LOCAL_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
